# Generated by Django 5.2.4 on 2025-07-25 06:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('order_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ModifyDoors',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('time_created', models.DateField()),
                ('site_status', models.CharField(choices=[('CR', 'Создан'), ('WR', 'Записан'), ('PR', 'Обработан'), ('CL', 'Закрыт')], default='CR', max_length=10, verbose_name='Статус заявки на сайте')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orders')),
            ],
        ),
    ]
