# Generated by Django 5.2.4 on 2025-07-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modifydoors',
            name='site_status',
            field=models.CharField(choices=[('CR', 'Создан'), ('WR', 'Записан'), ('PR', 'В работе'), ('CL', 'Закрыт')], default='CR', max_length=10, verbose_name='Статус заявки на сайте'),
        ),
    ]
